"""Move status column to ProfileNodeDetail

Revision ID: d6f5e6257a58
Revises: 3269884c7d8e
Create Date: 2025-08-23 22:47:23.277168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6f5e6257a58'
down_revision: Union[str, None] = '3269884c7d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'status')
    op.add_column(
        'profile_node_details', 
        sa.Column(
            'status', 
            sa.Enum('not_started', 'weak', 'neutral', 'strong', name='nodestatus'), 
            nullable=False, 
            # ✨ 이 부분을 추가해서 기존 데이터에 기본값을 설정해줍니다.
            server_default='not_started'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_node_details', 'status')
    op.add_column(
        'nodes', 
        sa.Column(
            'status', 
            postgresql.ENUM('not_started', 'weak', 'neutral', 'strong', name='nodestatus'), 
            autoincrement=False, 
            # downgrade 시에는 nullable=True로 바꿔주는 것이 더 안전합니다.
            nullable=True
        )
    )
    # ### end Alembic commands ###