"""Add difficulty to attempts table

Revision ID: fd485ec1b3dd
Revises: 891ddfa777df
Create Date: 2025-08-23 22:02:50.783261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd485ec1b3dd'
down_revision: Union[str, None] = '891ddfa777df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('difficulty', sa.String(), nullable=False))
    op.alter_column('nodes', 'status',
               existing_type=postgresql.ENUM('not_started', 'weak', 'neutral', 'strong', name='nodestatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'status',
               existing_type=postgresql.ENUM('not_started', 'weak', 'neutral', 'strong', name='nodestatus'),
               nullable=True)
    op.drop_column('attempts', 'difficulty')
    # ### end Alembic commands ###
